export const initialState = {
    AgesAllowed: 8,
    Alcohol: 4,
    Ambience: [false, false, false, false, false, false, false, false, false],
    BYOBCorkage: 1,
    BestNights: [false, false, false, false, false, false, false],
    BikeParking: [''],
    BusinessAcceptsBitcoin: [''],
    BusinessAcceptsCreditCards: [''],
    BusinessParking: [false, false, false, false, false],
    Caters: [''],
    CoatCheck: [''],
    DietaryRestrictions: [false, false, false, false],
    DogsAllowed: [''],
    DriveThru: [''],
    GoodForDancing: [''],
    GoodForKids: [''],
    GoodForMeal: [false, false, false, false, false, false],
    HairSpecializesIn: [''],
    HappyHour: [''],
    HasTV: [''],
    Music: [false, false, false, false, false, false],
    NoiseLevel: 16,
    Open24Hours: [''],
    OutdoorSeating: [''],
    RestaurantsAttire: 8,
    RestaurantsCounterService: [''],
    RestaurantsDelivery: [''],
    RestaurantsGoodForGroups: [''],
    RestaurantsPriceRange2: [''],
    RestaurantsReservations: [''],
    RestaurantsTableService: [''],
    RestaurantsTakeOut: [''],
    Smoking: [''],
    WheelchairAccessible: [''],
    WiFi: 1
};

export const stateList = [
    'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 
    'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 
    'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 
    'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'
]